In [1]:
import numpy as np
from numpy.random import randint as rnt

# 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
data=np.zeros(10,dtype="int64")
data[4]=1
data

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

# 2. Create a vector with values ranging from 10 to 49.

In [3]:
data2=np.arange(10,49)
data2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
data3=np.arange(0,9).reshape(3,3)
data3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [6]:
data4=np.array([1,2,0,0,4,0])
non_zero=data4.nonzero()
print("Non zero elements")
for i in non_zero[0]:
    print(f"{data4[i]} at index {i}")

Non zero elements
1 at index 0
2 at index 1
4 at index 4


# 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [7]:
data5=rnt(50,150,(10,10))
print(data5)
print(f"mininum value= {data5.min()}")
print(f"maximum value= {data5.max()}")

[[145 125 104 110 140 146 125 133  81 134]
 [ 83  74 101 118 112  94 117  61  67  88]
 [ 96 139  99 120 125  51  51 119 141  86]
 [ 54 123 114  87 129  94  84  56 145 121]
 [ 79 136  56 109  91  72  73  51 114  71]
 [ 80 101 110 117  89  71  51  66 142  71]
 [106 142  98  65 116 149  57 115 113 143]
 [102 107  60  91 148  96  94 120  88  60]
 [ 71 145  83 139  84 107 106 140 107  95]
 [117  60 106  67 146 140 104 117 136 108]]
mininum value= 51
maximum value= 149


# 6. Create a random vector of size 30 and find the mean value.

In [8]:
data6=rnt(10,100,30)
print(data6)
print(f"Mean = {data6.mean()}")

[75 45 81 75 52 87 33 70 10 10 49 34 58 12 31 76 74 67 60 84 56 39 17 90
 25 18 95 34 35 73]
Mean = 52.166666666666664
